version: "3"
services:
  ruby-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: habitus_reminders_ms
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: habitus_reminders_db
    ports:
      - "27017:27017"
