version: "3"
services:
  ruby-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: habitus_reminders_ms
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: habitus_reminders_db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: habitus_reminders_redis
    ports:
      - "6379:6379"
