check_notifications:
    cron: "*/1 * * * *" # every minute
    class: "CheckNotificationsWorker"
    queue: default
    description: "Check notifications every minute"
    output: log/check_notifications.log
