check_notifications:
    cron: "*/1 * * * *" # every 5 minutes
    class: "CheckNotificationsWorker"
    queue: default
    description: "Check notifications every 5 minutes"
    output: log/check_notifications.log
